import {useEffect,useState,useRef, type ReactNode} from 'react';
import {ArrowUpRight,ArrowRight,ArrowLeft,Menu,X,Sun,Moon,Check,Plus,Minus,ShieldCheck,Network,Database,SearchCheck,Files,ClipboardCheck,ScanSearch,Boxes,GraduationCap,GitBranch,ChartNoAxesCombined,ChevronDown,Linkedin,CheckCircle2,RotateCcw,ExternalLink} from 'lucide-react';
import {business,services,training,industries,timeline,testimonials,roadmap,questions,faqs} from './data';
import type {Service} from './data';
import Admin from './Admin';
import {PageHero,CTA,Challenges,About,Why,Roadmap,Industries,Training,Testimonials,AssessmentTeaser,Assessment,Insights,FAQ,Contact,Legal,ServiceContent,Modal,AuditTypes} from './features';

const icons={ShieldCheck,Network,Database,SearchCheck,Files,ClipboardCheck,ScanSearch,Boxes,GraduationCap,GitBranch,ChartNoAxesCombined};
export function Icon({name,size=25}:{name:string,size?:number}){const Component=icons[name as keyof typeof icons]||ShieldCheck;return <Component size={size} strokeWidth={1.4}/>}
export function Button({href,children,onClick,secondary=false,className=''}:{href?:string,children:ReactNode,onClick?:()=>void,secondary?:boolean,className?:string}){const cls=`button ${secondary?'secondary':''} ${className}`;return href?<a className={cls} href={href}>{children}<ArrowUpRight size={17}/></a>:<button className={cls} onClick={onClick}>{children}<ArrowUpRight size={17}/></button>}
function Header({path}:{path:string}){const [open,setOpen]=useState(false);const [dark,setDark]=useState(false);useEffect(()=>{setDark(document.documentElement.dataset.theme==='dark')},[]);function toggle(){const next=!dark;setDark(next);document.documentElement.dataset.theme=next?'dark':'light';try{localStorage.setItem('mdk-theme',next?'dark':'light')}catch{}}
const nav=[['About','/about'],['Services','/services'],['Industries','/industries'],['QMS Roadmap','/roadmap'],['Training','/training'],['Insights','/insights']];
return <><a href="#main" className="skip">Skip to content</a><header className="header"><a className="brand" href="/" aria-label="MDK home"><span className="brand-mark">MDK<span>✦</span><small>GLOBAL CONSULTANT</small></span><span className="brand-name">QUALITY MANAGEMENT<br/>SYSTEM CONSULTING</span></a><nav aria-label="Main navigation" className={open?'nav open':'nav'}>{nav.map(([label,url])=><a key={url} href={url} aria-current={path.startsWith(url)?'page':undefined}>{label}</a>)}<a className="mobile-only" href="/testimonials">Professional feedback</a><a className="mobile-only" href="/contact">Contact</a></nav><div className="header-actions"><button className="icon-button theme" onClick={toggle} aria-label="Toggle color theme">{dark?<Sun size={20}/>:<Moon size={20}/>}</button><Button href="/contact" className="header-cta">Book a consultation</Button><button className="icon-button menu-toggle" onClick={()=>setOpen(!open)} aria-label={open?'Close menu':'Open menu'} aria-expanded={open}>{open?<X/>:<Menu/>}</button></div></header></>}
const nodes=[['QMS','Connected quality processes and clear responsibilities.'],['Compliance','Understand applicable expectations and act on gaps.'],['Auditing','Examine evidence and identify opportunities to improve.'],['CAPA','Address causes and check the effectiveness of actions.'],['Data integrity','Data Integrity is the degree to which data are complete, consistent, accurate, trustworthy, reliable'],['Documentation','Keep documents complying to ALCOA+ requirements'],['Supplier quality','Connect qualification, risk and ongoing oversight.'],['Training','Build the understanding behind consistent practice.'],['Site Master File','Keep the site master file complete and current.'],['Quality Manual','Keep the quality manual aligned with the QMS.'],['Change control','Assess, approve and document changes.']];
function QualitySystem(){const [selected,setSelected]=useState(0);const ref=useRef<HTMLDivElement>(null);return <div className="system" ref={ref} onPointerMove={e=>{if(!matchMedia('(prefers-reduced-motion: reduce)').matches){const r=e.currentTarget.getBoundingClientRect();e.currentTarget.style.setProperty('--mx',`${(e.clientX-r.left-r.width/2)*.012}px`);e.currentTarget.style.setProperty('--my',`${(e.clientY-r.top-r.height/2)*.012}px`)}}} onPointerLeave={()=>{ref.current?.style.setProperty('--mx','0px');ref.current?.style.setProperty('--my','0px')}}><div className="system-heading"><span>THE QUALITY EXCELLENCE SYSTEM</span><span className="tiny-cross">+</span></div><div className="orbit"><svg viewBox="0 0 500 500" aria-hidden="true"><defs><marker id="quality-arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 1 1 L 9 5 L 1 9 z" fill="currentColor"/></marker></defs><circle className="orbit-ring" cx="250" cy="250" r="179"/><circle className="orbit-ring inner" cx="250" cy="250" r="114"/>{nodes.slice(1).map((_,i)=>{const a=(i*36-90)*Math.PI/180;return <line data-wheel-arrow={i+1} className={selected===i+1?'active-line':''} key={i} x1={250+Math.cos(a)*104} y1={250+Math.sin(a)*104} x2={250+Math.cos(a)*173} y2={250+Math.sin(a)*173} markerEnd="url(#quality-arrow)"/>})}<circle className="orbit-dash" cx="250" cy="250" r="224"/></svg><button className="qms-core" onClick={()=>setSelected(0)} aria-pressed={selected===0}><Network size={30}/><strong>QMS</strong><span>CONNECTED BY QUALITY</span></button>{nodes.slice(1).map(([label],i)=>{const a=(i*36-90)*Math.PI/180;return <button key={label} className={`node ${selected===i+1?'selected':''}`} style={{left:`${50+Math.cos(a)*35.8}%`,top:`${50+Math.sin(a)*35.8}%`}} onMouseEnter={()=>setSelected(i+1)} onFocus={()=>setSelected(i+1)} onClick={()=>setSelected(i+1)} aria-pressed={selected===i+1}><span className="node-dot"/>{label}</button>})}</div><div className="system-caption" aria-live="polite"><span className="caption-index">{String(selected).padStart(2,'0')} / 10</span><div><strong>{nodes[selected][0]}</strong><p>{nodes[selected][1]}</p></div><ArrowUpRight size={21}/></div></div>}
function HeroFeedback(){
 const [index,setIndex]=useState(0);
 const [paused,setPaused]=useState(false);
 useEffect(()=>{try{const last=Number(sessionStorage.getItem('mdk-hero-review')||'-1');setIndex((last+1)%testimonials.length)}catch{}},[]);
 useEffect(()=>{try{sessionStorage.setItem('mdk-hero-review',String(index))}catch{}},[index]);
 useEffect(()=>{if(paused||typeof window==='undefined'||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const timer=setInterval(()=>setIndex(i=>(i+1)%testimonials.length),8500);return()=>clearInterval(timer)},[paused]);
 const t=testimonials[index];
 return <div className="hero-feedback" onMouseEnter={()=>setPaused(true)} onMouseLeave={()=>setPaused(false)} onFocusCapture={()=>setPaused(true)} onBlurCapture={e=>{if(!e.currentTarget.contains(e.relatedTarget))setPaused(false)}}>
  <div className="hero-feedback-kicker"><span>PROFESSIONAL FEEDBACK</span><span>MDK / VOICES</span></div>
  <div className="hero-feedback-body" key={index} aria-live="polite"><div className="hero-review-person"><span className="review-initials" aria-hidden="true">{t.initials}</span><div><strong>{t.name}</strong><small>{t.org}</small></div></div><blockquote>“{t.quote}”</blockquote><p>{t.theme}</p></div>
  <div className="hero-feedback-footer"><span>{String(index+1).padStart(2,'0')} / {String(testimonials.length).padStart(2,'0')}</span><div><button type="button" aria-label="Previous professional review" onClick={()=>setIndex(i=>(i-1+testimonials.length)%testimonials.length)}><ArrowLeft size={18}/></button><button type="button" aria-label="Next professional review" onClick={()=>setIndex(i=>(i+1)%testimonials.length)}><ArrowRight size={18}/></button></div></div>
 </div>
}
function Hero(){return <section className="hero"><div className="hero-copy"><p className="eyebrow"><span/>QUALITY · COMPLIANCE · CONTINUOUS IMPROVEMENT</p><h1>Audit-ready quality systems<br/>for manufacturers</h1>
<p className="hero-description">Supplier and GMP audits, CAPA and data integrity support, and team training, led by a FSSC lead auditor with 150+ audits.</p><div className="hero-buttons"><Button href="/contact">Book a consultation</Button><a className="text-link" href="/services">Explore services <ArrowRight size={18}/></a></div><div className="hero-note"><span className="mini-mark">MK</span><span>Led by <strong>Megha Kandalkar</strong><br/>33+ years of professional experience in Pharma & FMCG</span></div></div><HeroFeedback/><div className="hero-bottom"><span>QUALITY IS A PRACTICE. MAKE IT YOUR CULTURE.</span><a href="#expertise">SCROLL TO EXPLORE <ChevronDown size={15}/></a></div></section>}
function Count({value}:{value:number}){const [shown,setShown]=useState(value);const ref=useRef<HTMLSpanElement>(null);useEffect(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;let frame=0;const observer=new IntersectionObserver(entries=>{if(entries[0].isIntersecting){const start=performance.now();function tick(now:number){const p=Math.min((now-start)/1100,1);setShown(Math.round(value*(1-Math.pow(1-p,3))));if(p<1)frame=requestAnimationFrame(tick)}frame=requestAnimationFrame(tick);observer.disconnect()}},{threshold:.6});if(ref.current)observer.observe(ref.current);return()=>{observer.disconnect();cancelAnimationFrame(frame)}},[value]);return <span ref={ref}>{shown}</span>}
function Authority(){return <section id="expertise" className="authority"><div><strong><Count value={33}/><sup>+</sup></strong><p>Years of professional<br/>experience</p></div><div><strong><Count value={150}/><sup>+</sup></strong><p>Audits completed<br/><b>Professional experience</b></p></div><div><ShieldCheck/><p>Pharma & FMCG<br/><strong>Industry perspective</strong></p></div><div><ClipboardCheck/><p>Chemical · Packaging · FNW · API<br/><strong>Audit experience</strong></p></div></section>}
function AmbientBackground(){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{let frame=0;const move=(e:PointerEvent)=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{ref.current?.style.setProperty('--pointer-x',e.clientX/innerWidth*100+'%');ref.current?.style.setProperty('--pointer-y',e.clientY/innerHeight*100+'%')})};addEventListener('pointermove',move,{passive:true});return()=>{removeEventListener('pointermove',move);cancelAnimationFrame(frame)}},[]);return <div ref={ref} className="ambient-bg" aria-hidden="true"><span className="ambient-orb one"/><span className="ambient-orb two"/><div className="ambient-grid"/><div className="ambient-pointer"/></div>}
export function SectionHead({label,title,copy,link}:{label:string,title:string,copy?:string,link?:[string,string]}){return <div className="section-head"><div><p className="eyebrow">{label}</p><h2>{title}</h2>{copy&&<p className="section-intro">{copy}</p>}</div>{link&&<a className="text-link" href={link[1]}>{link[0]}<ArrowUpRight size={18}/></a>}</div>}
function Services({full=false}:{full?:boolean}){const [selected,setSelected]=useState<Service|null>(null);return <section className="section" id="services"><SectionHead label="01 / OUR EXPERTISE" title="Quality systems built for the real world." copy="From the evidence in your records to the capability in your teams, bring clarity to every part of quality." link={full?undefined:['All services','/services']}/><div className="service-grid">{(full?services:services.slice(0,6)).map((s,i)=><article className="service-card" key={s.slug}><div className="card-top"><Icon name={s.icon}/><span>{String(i+1).padStart(2,'0')}</span></div><span className="card-tag">{s.tag}</span><h3><a href={'/services/'+s.slug}>{s.title}</a></h3><p>{s.short}</p><button className="card-bottom" onClick={()=>setSelected(s)} aria-label={'Explore '+s.title}>Explore service <ArrowUpRight size={20}/></button></article>)}</div>{selected&&<Modal title={selected.title} onClose={()=>setSelected(null)}><ServiceContent service={selected}/><a className="text-link modal-page-link" href={'/services/'+selected.slug}>Open service page<ArrowUpRight size={17}/></a></Modal>}</section>}
function Footer(){return <footer className="footer"><div className="footer-top"><div><a className="footer-logo" href="/">MDK<span>✦</span><small>GLOBAL CONSULTANT</small></a><p>Quality Management System Consulting</p><p className="footer-tagline">Compliance Simplified.<br/>Quality Amplified.</p></div><div><h3>COMPANY</h3><a href="/about">About MDK</a><a href="/about#journey">Professional journey</a><a href="/testimonials">Professional feedback</a><a href="/industries">Industries</a></div><div><h3>EXPERTISE</h3><a href="/services">Our services</a><a href="/training">Training</a><a href="/roadmap">QMS roadmap</a><a href="/contact">Book a consultation</a></div><div><h3>RESOURCES</h3><a href="/assessment">Quality self-assessment</a><a href="/insights">Insights</a><a href="/#faq">Frequently asked questions</a><a href={business.linkedin} target="_blank" rel="noopener noreferrer">LinkedIn <ExternalLink size={13}/></a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} MDK Quality Management System Consulting</span><div><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/disclaimer">Disclaimer</a><a href="/admin">Admin sign in</a></div></div><p className="fine-print">Information provided on this website is intended for general educational and consulting purposes. It should not be interpreted as a guarantee of certification, regulatory approval or audit outcome.</p></footer>}
export default function App({path='/' }:{path?:string}){path=path.replace(/\/$/,'')||'/';useEffect(()=>{const update=()=>{const max=document.documentElement.scrollHeight-innerHeight;document.documentElement.style.setProperty('--reading-progress',`${max>0?scrollY/max*100:0}%`)};update();addEventListener('scroll',update,{passive:true});const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in-view');obs.unobserve(e.target)}}),{threshold:.07});document.querySelectorAll('.section').forEach(e=>obs.observe(e));return()=>{removeEventListener('scroll',update);obs.disconnect()}},[]);
let content:ReactNode;const service=services.find(s=>path==='/services/'+s.slug);
if(path==='/')content=<><Hero/><Authority/><section className="section home-quality-section"><div><p className="eyebrow">THE QUALITY EXCELLENCE SYSTEM</p><h2>Quality works<br/>as one connected system.</h2><p className="section-intro">Explore ten connected quality practices. Select a point to see how it supports the wider system.</p></div><QualitySystem/></section><About/><Challenges/><Services/><AuditTypes/><Roadmap/><Why/><Industries/><Training compact/><AssessmentTeaser/><Insights/><FAQ/><CTA/><Contact compact/></>;
else if(service)content=<><PageHero label="OUR EXPERTISE" title={service.title} copy={service.short}/><section className="section service-page"><aside><p className="eyebrow">OUR SERVICES</p>{services.map(s=><a key={s.slug} href={'/services/'+s.slug} aria-current={s.slug===service.slug?'page':undefined}>{s.title}<ArrowUpRight size={14}/></a>)}</aside><article><ServiceContent service={service}/></article></section><CTA/></>;
else if(path==='/about')content=<><PageHero label="ABOUT MDK" title="Quality leadership, grounded in experience." copy="MDK Quality Management System Consulting brings Megha Kandalkar’s industry perspective to your quality challenges."/><About full/><Why/><Testimonials/><CTA/></>;
else if(path==='/services')content=<><PageHero label="OUR SERVICES" title="Bring clarity to every part of quality." copy="Explore practical support for your systems, evidence, people and improvement priorities."/><Services full/><AuditTypes/><Challenges/><Roadmap/><FAQ/><CTA/></>;
else if(path==='/industries')content=<><PageHero label="INDUSTRIES" title="Understand the context. Strengthen the system." copy="Quality support begins with your products, processes, people and the requirements relevant to your organization."/><Industries/><AuditTypes/><CTA/></>;
else if(path==='/roadmap')content=<><PageHero label="QMS ROADMAP" title="A connected approach to improvement." copy="Explore an illustrative quality journey and how connected practices can help derisk the business."/><Roadmap full/><section className="section wheel-section"><div><p className="eyebrow">THE COMPLIANCE WHEEL</p><h2>Every component<br/>supports the whole.</h2><p className="section-intro">Select a node to explore ten connected quality practices.</p></div><QualitySystem/></section><CTA/></>;
else if(path==='/training')content=<><PageHero label="TRAINING & CAPABILITY BUILDING" title="Understanding that becomes everyday practice." copy="Build concept clarity and practical quality awareness across your team. Explore topics by learning focus."/><Training/><CTA title="What does your team need to understand better?"/></>;
else if(path==='/testimonials')content=<><PageHero label="PROFESSIONAL FEEDBACK" title="A perspective from the people she’s worked with." copy="Selected, faithful excerpts from professional feedback on Megha Kandalkar’s auditing and quality work."/><Testimonials full/><CTA/></>;
else if(path==='/assessment')content=<><PageHero label="QUALITY SELF-ASSESSMENT" title="Know your starting point." copy="Ten questions about your current practices. A transparent quality maturity snapshot to help guide the next conversation."/><Assessment/></>;
else if(path==='/insights')content=<><PageHero label="KNOWLEDGE CENTRE" title="Quality, made clearer." copy="Planned perspectives on quality systems, records, auditing and continuous improvement."/><Insights/><FAQ/><CTA/></>;
else if(path==='/admin')content=<Admin/>;
else if(path==='/contact')content=<><PageHero label="BOOK A CONSULTATION" title="Let’s talk about your quality priorities." copy="A focused conversation is the first step toward a useful scope of work."/><Contact/><FAQ/></>;
else if(['/privacy','/terms','/disclaimer'].includes(path))content=<Legal kind={path.slice(1)}/>;
else content=<section className="section not-found"><p className="eyebrow">404 / PAGE NOT FOUND</p><h1>Looks like this process<br/>went outside the QMS.</h1><p>The page you’re looking for may have moved or doesn’t exist.</p><Button href="/">Return home</Button></section>;
return <><AmbientBackground/><div className="reading-progress" aria-hidden="true"/><Header path={path}/><main id="main">{content}</main><Footer/>{business.whatsapp&&<a className="whatsapp" href={'https://wa.me/'+business.whatsapp.replace(/\D/g,'')+'?text='+encodeURIComponent('Hello, I would like to enquire about MDK Quality Management System Consulting services.')} target="_blank" rel="noopener noreferrer">WhatsApp Business<ArrowUpRight size={15}/></a>}</>}

